### ISSUE TITLE
顶部的Header 有一点问题

### ISSUE THREAD

**Issue by zxx457** [Sansui233/Sansui233.github.io#2]
就是如果你滑的太快的话, 有时候滑到顶部了Header他也不下来, 然后你必须再滑下去 , 再慢慢滑上来

感觉是不是防抖时间有点长了

这是触发的视频
![Animation](https://user-images.githubusercontent.com/114141362/202377944-6eb165fb-d2e7-434c-a170-72a6be22c6a6.gif)

**Comment by Sansui233** [comment]
确实，防抖这个问题我调数值调了好久，现在好像是80ms，但还是有可能触发，只有10ms以内比较好（好像又没什么必要了）。我之前用的类似的主题类似功能没写防抖的。如果性能没什么问题，这一块还是不要太过于防抖交互会比较好= =
———
而且当系统带了滚动优化时，滚动的间隙更小了……

**Comment by zxx457** [comment]
> 确实，防抖这个问题我调数值调了好久，现在好像是80ms，但还是有可能触发，只有10ms以内比较好（好像又没什么必要了）。我之前用的类似的主题类似功能没写防抖的。如果性能没什么问题，这一块还是不要太过于防抖交互会比较好= = ——— 而且当系统带了滚动优化时，滚动的间隙更小了……

不好意思 , Issue 发错地方了 😢 

我看了repo https://github.com/Sansui233/blog/blob/8bd10a948dddd186b73604ba963e3f42c34dbb1b/components/Header.tsx#L34 是500毫秒, 是不是有点长了?

**Comment by Sansui233** [comment]
啊还真是……出现了错觉……80ms 还OK 的，感谢

**Comment by zxx457** [comment]
🫶
